import swaggerJsdoc from "swagger-jsdoc";
import path from "path";
import swaggerUi from "swagger-ui-express";

const docs = swaggerUi.setup(
  swaggerJsdoc({
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        title: "Peer Professor API",
        version: "1.0.0",
        description: "Express API with autogenerated swagger doc",
      },
    },
    // List of files to be processes
    apis: [path.join(__dirname, "./routes/*.js")],
  })
);

export { docs };
